### ISSUE TITLE
Definir estrutura de diretórios e arquivos MD para controle

### ISSUE THREAD

**Issue by francescosacco** [francescosacco/tk90x#1]
Olá, @rdays 

Precisamos definir a estrutura de diretórios do projeto.
Conforme conversamos, o objetivo final é ter um PDF com o esquema completo. Sugiro esse arquivo na raiz.

Sugiro que o README.md seja em inglês, e tenhamos um arquivo README.pt-br.md em português.

**Comment by francescosacco** [comment]
@rdays , veja se o commit 50745c65767b567f14dbecc11eed460eed66c6bf resolve o problema.

**Comment by rdays** [comment]
@francescosacco , o commit já incluiu as duas versões do arquivo README, tanto em inglês quanto em portugês, além de acrescentar o diretório "Documents" na estrutura de diretórios. Sendo assim, considero o issue resolvido.
